package cl.cesfam.ENTITY;
// Generated 22-05-2017 20:45:04 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Caducar generated by hbm2java
 */
public class Caducar  implements java.io.Serializable {


     private int idCaducar;
     private EstadoCaducar estadoCaducar;
     private FuncionarioFarmacia funcionarioFarmacia;
     private Medicamento medicamento;
     private Partida partida;
     private int cantidad;
     private Serializable fechaCaducar;
     private int motivoCaducar;

    public Caducar() {
    }

	
    public Caducar( int cantidad, Serializable fechaCaducar, int motivoCaducar) {
        this.cantidad = cantidad;
        this.fechaCaducar = fechaCaducar;
        this.motivoCaducar = motivoCaducar;
    }
    public Caducar(int idCaducar, EstadoCaducar estadoCaducar, FuncionarioFarmacia funcionarioFarmacia, Medicamento medicamento, Partida partida, int cantidad, Serializable fechaCaducar, int motivoCaducar) {
       this.idCaducar = idCaducar;
       this.estadoCaducar = estadoCaducar;
       this.funcionarioFarmacia = funcionarioFarmacia;
       this.medicamento = medicamento;
       this.partida = partida;
       this.cantidad = cantidad;
       this.fechaCaducar = fechaCaducar;
       this.motivoCaducar = motivoCaducar;
    }
   
    public int getIdCaducar() {
        return this.idCaducar;
    }
    
    public void setIdCaducar(int idCaducar) {
        this.idCaducar = idCaducar;
    }
    public EstadoCaducar getEstadoCaducar() {
        return this.estadoCaducar;
    }
    
    public void setEstadoCaducar(EstadoCaducar estadoCaducar) {
        this.estadoCaducar = estadoCaducar;
    }
    public FuncionarioFarmacia getFuncionarioFarmacia() {
        return this.funcionarioFarmacia;
    }
    
    public void setFuncionarioFarmacia(FuncionarioFarmacia funcionarioFarmacia) {
        this.funcionarioFarmacia = funcionarioFarmacia;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Serializable getFechaCaducar() {
        return this.fechaCaducar;
    }
    
    public void setFechaCaducar(Serializable fechaCaducar) {
        this.fechaCaducar = fechaCaducar;
    }
    public int getMotivoCaducar() {
        return this.motivoCaducar;
    }
    
    public void setMotivoCaducar(int motivoCaducar) {
        this.motivoCaducar = motivoCaducar;
    }




}


