package cl.cesfam.ENTITY;
// Generated 14-05-2017 18:10:14 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Caducar generated by hbm2java
 */
public class Caducar  implements java.io.Serializable {


     private int idCaducar;
     private FuncionarioFarmacia funcionarioFarmacia;
     private Medicamento medicamento;
     private Partida partida;
     private int cantidad;
     private Date fechaCaducar;
     private int motivoCaducar;
     private int estadoCaducar;

 
	
    public Caducar() {
     
    }
    public Caducar( FuncionarioFarmacia funcionarioFarmacia, Medicamento medicamento, Partida partida, int cantidad, Date fechaCaducar, int motivoCaducar, int estadoCaducar) {
       
       this.funcionarioFarmacia = funcionarioFarmacia;
       this.medicamento = medicamento;
       this.partida = partida;
       this.cantidad = cantidad;
       this.fechaCaducar = fechaCaducar;
       this.motivoCaducar = motivoCaducar;
       this.estadoCaducar = estadoCaducar;
    }
   
    public int getIdCaducar() {
        return this.idCaducar;
    }
    
    public void setIdCaducar(int idCaducar) {
        this.idCaducar = idCaducar;
    }
    public FuncionarioFarmacia getFuncionarioFarmacia() {
        return this.funcionarioFarmacia;
    }
    
    public void setFuncionarioFarmacia(FuncionarioFarmacia funcionarioFarmacia) {
        this.funcionarioFarmacia = funcionarioFarmacia;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaCaducar() {
        return this.fechaCaducar;
    }
    
    public void setFechaCaducar(Date fechaCaducar) {
        this.fechaCaducar = fechaCaducar;
    }
    public int getMotivoCaducar() {
        return this.motivoCaducar;
    }
    
    public void setMotivoCaducar(int motivoCaducar) {
        this.motivoCaducar = motivoCaducar;
    }
    public int getEstadoCaducar() {
        return this.estadoCaducar;
    }
    
    public void setEstadoCaducar(int estadoCaducar) {
        this.estadoCaducar = estadoCaducar;
    }




}


