package cl.cesfam.ENTITY;
// Generated 25-05-2017 9:08:39 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Caducar generated by hbm2java
 */
public class Caducar  {


     private int idCaducar;
     private EstadoCaducar estadoCaducar;
     private FuncionarioFarmacia funcionarioFarmacia;
     private Medicamento medicamento;
     private Partida partida;
     private MotivoCaducar motivoCaducar;
     private int cantidad;
     private Date fechaCaducar;

    public Caducar() {
    }

	
    public Caducar(int idCaducar, int cantidad, Date fechaCaducar) {
        this.idCaducar = idCaducar;
        this.cantidad = cantidad;
        this.fechaCaducar = fechaCaducar;
    }
    public Caducar(int idCaducar, EstadoCaducar estadoCaducar, FuncionarioFarmacia funcionarioFarmacia, Medicamento medicamento, Partida partida, MotivoCaducar motivoCaducar, int cantidad, Date fechaCaducar) {
       this.idCaducar = idCaducar;
       this.estadoCaducar = estadoCaducar;
       this.funcionarioFarmacia = funcionarioFarmacia;
       this.medicamento = medicamento;
       this.partida = partida;
       this.motivoCaducar = motivoCaducar;
       this.cantidad = cantidad;
       this.fechaCaducar = fechaCaducar;
    }
   
    public int getIdCaducar() {
        return this.idCaducar;
    }
    
    public void setIdCaducar(int idCaducar) {
        this.idCaducar = idCaducar;
    }
    public EstadoCaducar getEstadoCaducar() {
        return this.estadoCaducar;
    }
    
    public void setEstadoCaducar(EstadoCaducar estadoCaducar) {
        this.estadoCaducar = estadoCaducar;
    }
    public FuncionarioFarmacia getFuncionarioFarmacia() {
        return this.funcionarioFarmacia;
    }
    
    public void setFuncionarioFarmacia(FuncionarioFarmacia funcionarioFarmacia) {
        this.funcionarioFarmacia = funcionarioFarmacia;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public MotivoCaducar getMotivoCaducar() {
        return this.motivoCaducar;
    }
    
    public void setMotivoCaducar(MotivoCaducar motivoCaducar) {
        this.motivoCaducar = motivoCaducar;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaCaducar() {
        return this.fechaCaducar;
    }
    
    public void setFechaCaducar(Date fechaCaducar) {
        this.fechaCaducar = fechaCaducar;
    }




}


