package cl.cesfam.ENTITY;
// Generated 16-04-2017 15:22:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Componente generated by hbm2java
 */
public class Componente  implements java.io.Serializable {


     private BigDecimal idComponente;
     private String nombreComponente;
     private Set composicions = new HashSet(0);

    public Componente() {
    }

	
    public Componente(BigDecimal idComponente, String nombreComponente) {
        this.idComponente = idComponente;
        this.nombreComponente = nombreComponente;
    }
    public Componente(BigDecimal idComponente, String nombreComponente, Set composicions) {
       this.idComponente = idComponente;
       this.nombreComponente = nombreComponente;
       this.composicions = composicions;
    }
   
    public BigDecimal getIdComponente() {
        return this.idComponente;
    }
    
    public void setIdComponente(BigDecimal idComponente) {
        this.idComponente = idComponente;
    }
    public String getNombreComponente() {
        return this.nombreComponente;
    }
    
    public void setNombreComponente(String nombreComponente) {
        this.nombreComponente = nombreComponente;
    }
    public Set getComposicions() {
        return this.composicions;
    }
    
    public void setComposicions(Set composicions) {
        this.composicions = composicions;
    }




}


