package cl.cesfam.ENTITY;
// Generated 14-04-2017 22:03:42 by Hibernate Tools 4.3.1



/**
 * Componente generated by hbm2java
 */
public class Componente  implements java.io.Serializable {


     private long idComponente;
     private String nombreComponente;
     private long cantidadComponente;

    public Componente() {
    }

    public Componente(long idComponente, String nombreComponente, long cantidadComponente) {
       this.idComponente = idComponente;
       this.nombreComponente = nombreComponente;
       this.cantidadComponente = cantidadComponente;
    }
   
    public long getIdComponente() {
        return this.idComponente;
    }
    
    public void setIdComponente(long idComponente) {
        this.idComponente = idComponente;
    }
    public String getNombreComponente() {
        return this.nombreComponente;
    }
    
    public void setNombreComponente(String nombreComponente) {
        this.nombreComponente = nombreComponente;
    }
    public long getCantidadComponente() {
        return this.cantidadComponente;
    }
    
    public void setCantidadComponente(long cantidadComponente) {
        this.cantidadComponente = cantidadComponente;
    }




}


