package cl.cesfam.entity;
// Generated 16-04-2017 14:22:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Composicion generated by hbm2java
 */
public class Composicion  implements java.io.Serializable {


     private BigDecimal idComposicion;
     private Componente componente;
     private Medicamento medicamento;
     private BigDecimal cantidad;

    public Composicion() {
    }

	
    public Composicion(BigDecimal idComposicion) {
        this.idComposicion = idComposicion;
    }
    public Composicion(BigDecimal idComposicion, Componente componente, Medicamento medicamento, BigDecimal cantidad) {
       this.idComposicion = idComposicion;
       this.componente = componente;
       this.medicamento = medicamento;
       this.cantidad = cantidad;
    }
   
    public BigDecimal getIdComposicion() {
        return this.idComposicion;
    }
    
    public void setIdComposicion(BigDecimal idComposicion) {
        this.idComposicion = idComposicion;
    }
    public Componente getComponente() {
        return this.componente;
    }
    
    public void setComponente(Componente componente) {
        this.componente = componente;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


