package cl.cesfam.ENTITY;
// Generated 16-04-2017 15:22:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DetallePartida generated by hbm2java
 */
public class DetallePartida  implements java.io.Serializable {


     private BigDecimal idDetallePartida;
     private Medicamento medicamento;
     private Partida partida;
     private BigDecimal cantidad;
     private Date fechaIngreso;

    public DetallePartida() {
    }

	
    public DetallePartida(BigDecimal idDetallePartida, BigDecimal cantidad, Date fechaIngreso) {
        this.idDetallePartida = idDetallePartida;
        this.cantidad = cantidad;
        this.fechaIngreso = fechaIngreso;
    }
    public DetallePartida(BigDecimal idDetallePartida, Medicamento medicamento, Partida partida, BigDecimal cantidad, Date fechaIngreso) {
       this.idDetallePartida = idDetallePartida;
       this.medicamento = medicamento;
       this.partida = partida;
       this.cantidad = cantidad;
       this.fechaIngreso = fechaIngreso;
    }
   
    public BigDecimal getIdDetallePartida() {
        return this.idDetallePartida;
    }
    
    public void setIdDetallePartida(BigDecimal idDetallePartida) {
        this.idDetallePartida = idDetallePartida;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }




}


