package cl.cesfam.ENTITY;
// Generated 14-04-2017 22:03:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetallePartida generated by hbm2java
 */
public class DetallePartida  implements java.io.Serializable {


     private long idDetallePartida;
     private Medicamento medicamento;
     private Partida partida;
     private long cantidad;
     private Date fechaIngreso;

    public DetallePartida() {
    }

	
    public DetallePartida(long idDetallePartida, long cantidad, Date fechaIngreso) {
        this.idDetallePartida = idDetallePartida;
        this.cantidad = cantidad;
        this.fechaIngreso = fechaIngreso;
    }
    public DetallePartida(long idDetallePartida, Medicamento medicamento, Partida partida, long cantidad, Date fechaIngreso) {
       this.idDetallePartida = idDetallePartida;
       this.medicamento = medicamento;
       this.partida = partida;
       this.cantidad = cantidad;
       this.fechaIngreso = fechaIngreso;
    }
   
    public long getIdDetallePartida() {
        return this.idDetallePartida;
    }
    
    public void setIdDetallePartida(long idDetallePartida) {
        this.idDetallePartida = idDetallePartida;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(long cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }




}


