package cl.cesfam.ENTITY;
// Generated 16-04-2017 15:22:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleEntrega generated by hbm2java
 */
public class DetalleEntrega  implements java.io.Serializable {


     private BigDecimal idEntrega;
     private Partida partida;
     private BigDecimal entregaIdEntrega;
     private BigDecimal prescripcionIdPrescripcion;

    public DetalleEntrega() {
    }

	
    public DetalleEntrega(BigDecimal idEntrega) {
        this.idEntrega = idEntrega;
    }
    public DetalleEntrega(BigDecimal idEntrega, Partida partida, BigDecimal entregaIdEntrega, BigDecimal prescripcionIdPrescripcion) {
       this.idEntrega = idEntrega;
       this.partida = partida;
       this.entregaIdEntrega = entregaIdEntrega;
       this.prescripcionIdPrescripcion = prescripcionIdPrescripcion;
    }
   
    public BigDecimal getIdEntrega() {
        return this.idEntrega;
    }
    
    public void setIdEntrega(BigDecimal idEntrega) {
        this.idEntrega = idEntrega;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public BigDecimal getEntregaIdEntrega() {
        return this.entregaIdEntrega;
    }
    
    public void setEntregaIdEntrega(BigDecimal entregaIdEntrega) {
        this.entregaIdEntrega = entregaIdEntrega;
    }
    public BigDecimal getPrescripcionIdPrescripcion() {
        return this.prescripcionIdPrescripcion;
    }
    
    public void setPrescripcionIdPrescripcion(BigDecimal prescripcionIdPrescripcion) {
        this.prescripcionIdPrescripcion = prescripcionIdPrescripcion;
    }




}


