package cl.cesfam.ENTITY;
// Generated 16-04-2017 17:23:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetallePartida generated by hbm2java
 */
public class DetallePartida  implements java.io.Serializable {


     private int idDetallePartida;
     private Medicamento medicamento;
     private Partida partida;
     private int cantidad;
     private Date fechaIngreso;

    public DetallePartida() {
    }

	
    public DetallePartida( int cantidad, Date fechaIngreso) {
        
        this.cantidad = cantidad;
        this.fechaIngreso = fechaIngreso;
    }
    public DetallePartida(Medicamento medicamento, Partida partida, int cantidad, Date fechaIngreso) {
       
       this.medicamento = medicamento;
       this.partida = partida;
       this.cantidad = cantidad;
       this.fechaIngreso = fechaIngreso;
    }
   
    public int getIdDetallePartida() {
        return this.idDetallePartida;
    }
    
    public void setIdDetallePartida(int idDetallePartida) {
        this.idDetallePartida = idDetallePartida;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }




}


