package cl.cesfam.ENTITY;
// Generated 14-04-2017 22:03:42 by Hibernate Tools 4.3.1



/**
 * DetalleEntrega generated by hbm2java
 */
public class DetalleEntrega  implements java.io.Serializable {


     private long idEntrega;
     private Partida partida;
     private Long entregaIdEntrega;
     private Long prescripcionIdPrescripcion;

    public DetalleEntrega() {
    }

	
    public DetalleEntrega(long idEntrega) {
        this.idEntrega = idEntrega;
    }
    public DetalleEntrega(long idEntrega, Partida partida, Long entregaIdEntrega, Long prescripcionIdPrescripcion) {
       this.idEntrega = idEntrega;
       this.partida = partida;
       this.entregaIdEntrega = entregaIdEntrega;
       this.prescripcionIdPrescripcion = prescripcionIdPrescripcion;
    }
   
    public long getIdEntrega() {
        return this.idEntrega;
    }
    
    public void setIdEntrega(long idEntrega) {
        this.idEntrega = idEntrega;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public Long getEntregaIdEntrega() {
        return this.entregaIdEntrega;
    }
    
    public void setEntregaIdEntrega(Long entregaIdEntrega) {
        this.entregaIdEntrega = entregaIdEntrega;
    }
    public Long getPrescripcionIdPrescripcion() {
        return this.prescripcionIdPrescripcion;
    }
    
    public void setPrescripcionIdPrescripcion(Long prescripcionIdPrescripcion) {
        this.prescripcionIdPrescripcion = prescripcionIdPrescripcion;
    }




}


