package cl.cesfam.ENTITY;
// Generated 22-05-2017 20:45:04 by Hibernate Tools 4.3.1



/**
 * DetalleEntrega generated by hbm2java
 */
public class DetalleEntrega  implements java.io.Serializable {


     private int idEntrega;
     private Partida partida;
     private int entregaIdEntrega;
     private int prescripcionIdPrescripcion;

    public DetalleEntrega() {
    }

	
    public DetalleEntrega(int idEntrega) {
        this.idEntrega = idEntrega;
    }
    public DetalleEntrega(int idEntrega, Partida partida, Integer entregaIdEntrega, Integer prescripcionIdPrescripcion) {
       this.idEntrega = idEntrega;
       this.partida = partida;
       this.entregaIdEntrega = entregaIdEntrega;
       this.prescripcionIdPrescripcion = prescripcionIdPrescripcion;
    }
   
    public int getIdEntrega() {
        return this.idEntrega;
    }
    
    public void setIdEntrega(int idEntrega) {
        this.idEntrega = idEntrega;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public Integer getEntregaIdEntrega() {
        return this.entregaIdEntrega;
    }
    
    public void setEntregaIdEntrega(int entregaIdEntrega) {
        this.entregaIdEntrega = entregaIdEntrega;
    }
    public int getPrescripcionIdPrescripcion() {
        return this.prescripcionIdPrescripcion;
    }
    
    public void setPrescripcionIdPrescripcion(int prescripcionIdPrescripcion) {
        this.prescripcionIdPrescripcion = prescripcionIdPrescripcion;
    }




}


