package cl.cesfam.ENTITY;
// Generated 22-05-2017 20:45:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoEventoStock generated by hbm2java
 */
public class EstadoEventoStock  implements java.io.Serializable {


     private int idEstadoEventoStock;
     private String nombreEstado;
     private Set eventoStocks = new HashSet(0);

    public EstadoEventoStock() {
    }

	
    public EstadoEventoStock(int idEstadoEventoStock, String nombreEstado) {
        this.idEstadoEventoStock = idEstadoEventoStock;
        this.nombreEstado = nombreEstado;
    }
    public EstadoEventoStock(int idEstadoEventoStock, String nombreEstado, Set eventoStocks) {
       this.idEstadoEventoStock = idEstadoEventoStock;
       this.nombreEstado = nombreEstado;
       this.eventoStocks = eventoStocks;
    }
   
    public int getIdEstadoEventoStock() {
        return this.idEstadoEventoStock;
    }
    
    public void setIdEstadoEventoStock(int idEstadoEventoStock) {
        this.idEstadoEventoStock = idEstadoEventoStock;
    }
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }
    public Set getEventoStocks() {
        return this.eventoStocks;
    }
    
    public void setEventoStocks(Set eventoStocks) {
        this.eventoStocks = eventoStocks;
    }




}


