package cl.cesfam.ENTITY;
// Generated 22-05-2017 20:45:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoPrescripcion generated by hbm2java
 */
public class EstadoPrescripcion  implements java.io.Serializable {


     private int idEstadoPrescripcion;
     private String nombre;
     private Set prescripcions = new HashSet(0);

    public EstadoPrescripcion() {
    }

	
    public EstadoPrescripcion(int idEstadoPrescripcion, String nombre) {
        this.idEstadoPrescripcion = idEstadoPrescripcion;
        this.nombre = nombre;
    }
    public EstadoPrescripcion(int idEstadoPrescripcion, String nombre, Set prescripcions) {
       this.idEstadoPrescripcion = idEstadoPrescripcion;
       this.nombre = nombre;
       this.prescripcions = prescripcions;
    }
   
    public int getIdEstadoPrescripcion() {
        return this.idEstadoPrescripcion;
    }
    
    public void setIdEstadoPrescripcion(int idEstadoPrescripcion) {
        this.idEstadoPrescripcion = idEstadoPrescripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPrescripcions() {
        return this.prescripcions;
    }
    
    public void setPrescripcions(Set prescripcions) {
        this.prescripcions = prescripcions;
    }




}


