package cl.cesfam.ENTITY;
// Generated 22-05-2017 20:45:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoReserva generated by hbm2java
 */
public class EstadoReserva  {


     private int idEstadoReserva;
     private String nombreEstado;
     private Set reserva = new HashSet(0);

    public EstadoReserva() {
    }

	
    public EstadoReserva(int idEstadoEventoStock, String nombreEstado) {
        this.idEstadoReserva = idEstadoEventoStock;
        this.nombreEstado = nombreEstado;
    }
    public EstadoReserva(int idEstadoEventoStock, String nombreEstado, Set reserva) {
       this.idEstadoReserva = idEstadoEventoStock;
       this.nombreEstado = nombreEstado;
       this.reserva = reserva;
    }
   
    public int getIdEstadoReserva() {
        return this.idEstadoReserva;
    }
    
    public void setIdEstadoReserva(int idEstadoReserva) {
        this.idEstadoReserva = idEstadoReserva;
    }
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }
    public Set getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Set reserva) {
        this.reserva = reserva;
    }




}


