package cl.cesfam.ENTITY;
// Generated 16-04-2017 15:22:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EventoStock generated by hbm2java
 */
public class EventoStock  implements java.io.Serializable {


     private BigDecimal idEventoStock;
     private Medicamento medicamento;
     private Paciente paciente;
     private Date fechaEventoStock;
     private char reserva;
     private String observacion;
     private BigDecimal estado;

    public EventoStock() {
    }

	
    public EventoStock(BigDecimal idEventoStock, Date fechaEventoStock, char reserva, BigDecimal estado) {
        this.idEventoStock = idEventoStock;
        this.fechaEventoStock = fechaEventoStock;
        this.reserva = reserva;
        this.estado = estado;
    }
    public EventoStock(BigDecimal idEventoStock, Medicamento medicamento, Paciente paciente, Date fechaEventoStock, char reserva, String observacion, BigDecimal estado) {
       this.idEventoStock = idEventoStock;
       this.medicamento = medicamento;
       this.paciente = paciente;
       this.fechaEventoStock = fechaEventoStock;
       this.reserva = reserva;
       this.observacion = observacion;
       this.estado = estado;
    }
   
    public BigDecimal getIdEventoStock() {
        return this.idEventoStock;
    }
    
    public void setIdEventoStock(BigDecimal idEventoStock) {
        this.idEventoStock = idEventoStock;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getFechaEventoStock() {
        return this.fechaEventoStock;
    }
    
    public void setFechaEventoStock(Date fechaEventoStock) {
        this.fechaEventoStock = fechaEventoStock;
    }
    public char getReserva() {
        return this.reserva;
    }
    
    public void setReserva(char reserva) {
        this.reserva = reserva;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public BigDecimal getEstado() {
        return this.estado;
    }
    
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }




}


