package cl.cesfam.ENTITY;
// Generated 16-04-2017 15:22:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * FormularioMediamento generated by hbm2java
 */
public class FormularioMediamento  implements java.io.Serializable {


     private BigDecimal idFormularioMedicamento;
     private BigDecimal cantidadEntregada;
     private char requiereProximaEvaluacion;
     private Date fechaProximaEvaluacion;
     private BigDecimal medicoIdMedico;
     private BigDecimal pacienteIdPaciente;

    public FormularioMediamento() {
    }

	
    public FormularioMediamento(BigDecimal idFormularioMedicamento, BigDecimal cantidadEntregada, char requiereProximaEvaluacion) {
        this.idFormularioMedicamento = idFormularioMedicamento;
        this.cantidadEntregada = cantidadEntregada;
        this.requiereProximaEvaluacion = requiereProximaEvaluacion;
    }
    public FormularioMediamento(BigDecimal idFormularioMedicamento, BigDecimal cantidadEntregada, char requiereProximaEvaluacion, Date fechaProximaEvaluacion, BigDecimal medicoIdMedico, BigDecimal pacienteIdPaciente) {
       this.idFormularioMedicamento = idFormularioMedicamento;
       this.cantidadEntregada = cantidadEntregada;
       this.requiereProximaEvaluacion = requiereProximaEvaluacion;
       this.fechaProximaEvaluacion = fechaProximaEvaluacion;
       this.medicoIdMedico = medicoIdMedico;
       this.pacienteIdPaciente = pacienteIdPaciente;
    }
   
    public BigDecimal getIdFormularioMedicamento() {
        return this.idFormularioMedicamento;
    }
    
    public void setIdFormularioMedicamento(BigDecimal idFormularioMedicamento) {
        this.idFormularioMedicamento = idFormularioMedicamento;
    }
    public BigDecimal getCantidadEntregada() {
        return this.cantidadEntregada;
    }
    
    public void setCantidadEntregada(BigDecimal cantidadEntregada) {
        this.cantidadEntregada = cantidadEntregada;
    }
    public char getRequiereProximaEvaluacion() {
        return this.requiereProximaEvaluacion;
    }
    
    public void setRequiereProximaEvaluacion(char requiereProximaEvaluacion) {
        this.requiereProximaEvaluacion = requiereProximaEvaluacion;
    }
    public Date getFechaProximaEvaluacion() {
        return this.fechaProximaEvaluacion;
    }
    
    public void setFechaProximaEvaluacion(Date fechaProximaEvaluacion) {
        this.fechaProximaEvaluacion = fechaProximaEvaluacion;
    }
    public BigDecimal getMedicoIdMedico() {
        return this.medicoIdMedico;
    }
    
    public void setMedicoIdMedico(BigDecimal medicoIdMedico) {
        this.medicoIdMedico = medicoIdMedico;
    }
    public BigDecimal getPacienteIdPaciente() {
        return this.pacienteIdPaciente;
    }
    
    public void setPacienteIdPaciente(BigDecimal pacienteIdPaciente) {
        this.pacienteIdPaciente = pacienteIdPaciente;
    }




}


