package cl.cesfam.ENTITY;
// Generated 14-04-2017 22:03:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FormularioMediamento generated by hbm2java
 */
public class FormularioMediamento  implements java.io.Serializable {


     private long idFormularioMedicamento;
     private long cantidadEntregada;
     private char requiereProximaEvaluacion;
     private Date fechaProximaEvaluacion;
     private Long medicoIdMedico;
     private Long pacienteIdPaciente;

    public FormularioMediamento() {
    }

	
    public FormularioMediamento(long idFormularioMedicamento, long cantidadEntregada, char requiereProximaEvaluacion) {
        this.idFormularioMedicamento = idFormularioMedicamento;
        this.cantidadEntregada = cantidadEntregada;
        this.requiereProximaEvaluacion = requiereProximaEvaluacion;
    }
    public FormularioMediamento(long idFormularioMedicamento, long cantidadEntregada, char requiereProximaEvaluacion, Date fechaProximaEvaluacion, Long medicoIdMedico, Long pacienteIdPaciente) {
       this.idFormularioMedicamento = idFormularioMedicamento;
       this.cantidadEntregada = cantidadEntregada;
       this.requiereProximaEvaluacion = requiereProximaEvaluacion;
       this.fechaProximaEvaluacion = fechaProximaEvaluacion;
       this.medicoIdMedico = medicoIdMedico;
       this.pacienteIdPaciente = pacienteIdPaciente;
    }
   
    public long getIdFormularioMedicamento() {
        return this.idFormularioMedicamento;
    }
    
    public void setIdFormularioMedicamento(long idFormularioMedicamento) {
        this.idFormularioMedicamento = idFormularioMedicamento;
    }
    public long getCantidadEntregada() {
        return this.cantidadEntregada;
    }
    
    public void setCantidadEntregada(long cantidadEntregada) {
        this.cantidadEntregada = cantidadEntregada;
    }
    public char getRequiereProximaEvaluacion() {
        return this.requiereProximaEvaluacion;
    }
    
    public void setRequiereProximaEvaluacion(char requiereProximaEvaluacion) {
        this.requiereProximaEvaluacion = requiereProximaEvaluacion;
    }
    public Date getFechaProximaEvaluacion() {
        return this.fechaProximaEvaluacion;
    }
    
    public void setFechaProximaEvaluacion(Date fechaProximaEvaluacion) {
        this.fechaProximaEvaluacion = fechaProximaEvaluacion;
    }
    public Long getMedicoIdMedico() {
        return this.medicoIdMedico;
    }
    
    public void setMedicoIdMedico(Long medicoIdMedico) {
        this.medicoIdMedico = medicoIdMedico;
    }
    public Long getPacienteIdPaciente() {
        return this.pacienteIdPaciente;
    }
    
    public void setPacienteIdPaciente(Long pacienteIdPaciente) {
        this.pacienteIdPaciente = pacienteIdPaciente;
    }




}


