package cl.cesfam.ENTITY;
// Generated 22-05-2017 20:45:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FormularioMediamento generated by hbm2java
 */
public class FormularioMediamento  implements java.io.Serializable {


     private int idFormularioMedicamento;
     private int cantidadEntregada;
     private char requiereProximaEvaluacion;
     private Date fechaProximaEvaluacion;
     private Integer medicoIdMedico;
     private Integer pacienteIdPaciente;
     private Set prescripcions = new HashSet(0);

    public FormularioMediamento() {
    }

	
    public FormularioMediamento(int idFormularioMedicamento, int cantidadEntregada, char requiereProximaEvaluacion) {
        this.idFormularioMedicamento = idFormularioMedicamento;
        this.cantidadEntregada = cantidadEntregada;
        this.requiereProximaEvaluacion = requiereProximaEvaluacion;
    }
    public FormularioMediamento(int idFormularioMedicamento, int cantidadEntregada, char requiereProximaEvaluacion, Date fechaProximaEvaluacion, Integer medicoIdMedico, Integer pacienteIdPaciente, Set prescripcions) {
       this.idFormularioMedicamento = idFormularioMedicamento;
       this.cantidadEntregada = cantidadEntregada;
       this.requiereProximaEvaluacion = requiereProximaEvaluacion;
       this.fechaProximaEvaluacion = fechaProximaEvaluacion;
       this.medicoIdMedico = medicoIdMedico;
       this.pacienteIdPaciente = pacienteIdPaciente;
       this.prescripcions = prescripcions;
    }
   
    public int getIdFormularioMedicamento() {
        return this.idFormularioMedicamento;
    }
    
    public void setIdFormularioMedicamento(int idFormularioMedicamento) {
        this.idFormularioMedicamento = idFormularioMedicamento;
    }
    public int getCantidadEntregada() {
        return this.cantidadEntregada;
    }
    
    public void setCantidadEntregada(int cantidadEntregada) {
        this.cantidadEntregada = cantidadEntregada;
    }
    public char getRequiereProximaEvaluacion() {
        return this.requiereProximaEvaluacion;
    }
    
    public void setRequiereProximaEvaluacion(char requiereProximaEvaluacion) {
        this.requiereProximaEvaluacion = requiereProximaEvaluacion;
    }
    public Date getFechaProximaEvaluacion() {
        return this.fechaProximaEvaluacion;
    }
    
    public void setFechaProximaEvaluacion(Date fechaProximaEvaluacion) {
        this.fechaProximaEvaluacion = fechaProximaEvaluacion;
    }
    public Integer getMedicoIdMedico() {
        return this.medicoIdMedico;
    }
    
    public void setMedicoIdMedico(Integer medicoIdMedico) {
        this.medicoIdMedico = medicoIdMedico;
    }
    public Integer getPacienteIdPaciente() {
        return this.pacienteIdPaciente;
    }
    
    public void setPacienteIdPaciente(Integer pacienteIdPaciente) {
        this.pacienteIdPaciente = pacienteIdPaciente;
    }
    public Set getPrescripcions() {
        return this.prescripcions;
    }
    
    public void setPrescripcions(Set prescripcions) {
        this.prescripcions = prescripcions;
    }




}


