package cl.cesfam.ENTITY;
// Generated 16-04-2017 15:22:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FuncionarioFarmacia generated by hbm2java
 */
public class FuncionarioFarmacia  implements java.io.Serializable {


     private BigDecimal idFuncionario;
     private String rutFuncionario;
     private String password;
     private String primerNombreFuncionario;
     private String sengundoNombreFuncionario;
     private String apellidoPaternoFuncionario;
     private String apellidoMaternoFuncionario;

    public FuncionarioFarmacia() {
    }

	
    public FuncionarioFarmacia(BigDecimal idFuncionario, String rutFuncionario, String password, String primerNombreFuncionario, String apellidoPaternoFuncionario, String apellidoMaternoFuncionario) {
        this.idFuncionario = idFuncionario;
        this.rutFuncionario = rutFuncionario;
        this.password = password;
        this.primerNombreFuncionario = primerNombreFuncionario;
        this.apellidoPaternoFuncionario = apellidoPaternoFuncionario;
        this.apellidoMaternoFuncionario = apellidoMaternoFuncionario;
    }
    public FuncionarioFarmacia(BigDecimal idFuncionario, String rutFuncionario, String password, String primerNombreFuncionario, String sengundoNombreFuncionario, String apellidoPaternoFuncionario, String apellidoMaternoFuncionario) {
       this.idFuncionario = idFuncionario;
       this.rutFuncionario = rutFuncionario;
       this.password = password;
       this.primerNombreFuncionario = primerNombreFuncionario;
       this.sengundoNombreFuncionario = sengundoNombreFuncionario;
       this.apellidoPaternoFuncionario = apellidoPaternoFuncionario;
       this.apellidoMaternoFuncionario = apellidoMaternoFuncionario;
    }
   
    public BigDecimal getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(BigDecimal idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public String getRutFuncionario() {
        return this.rutFuncionario;
    }
    
    public void setRutFuncionario(String rutFuncionario) {
        this.rutFuncionario = rutFuncionario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPrimerNombreFuncionario() {
        return this.primerNombreFuncionario;
    }
    
    public void setPrimerNombreFuncionario(String primerNombreFuncionario) {
        this.primerNombreFuncionario = primerNombreFuncionario;
    }
    public String getSengundoNombreFuncionario() {
        return this.sengundoNombreFuncionario;
    }
    
    public void setSengundoNombreFuncionario(String sengundoNombreFuncionario) {
        this.sengundoNombreFuncionario = sengundoNombreFuncionario;
    }
    public String getApellidoPaternoFuncionario() {
        return this.apellidoPaternoFuncionario;
    }
    
    public void setApellidoPaternoFuncionario(String apellidoPaternoFuncionario) {
        this.apellidoPaternoFuncionario = apellidoPaternoFuncionario;
    }
    public String getApellidoMaternoFuncionario() {
        return this.apellidoMaternoFuncionario;
    }
    
    public void setApellidoMaternoFuncionario(String apellidoMaternoFuncionario) {
        this.apellidoMaternoFuncionario = apellidoMaternoFuncionario;
    }




}


