package cl.cesfam.ENTITY;
// Generated 14-04-2017 22:03:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medicamento generated by hbm2java
 */
public class Medicamento  implements java.io.Serializable {


     private long idMedicamento;
     private Stock stock;
     private String nombreMedicamento;
     private long presentacion;
     private long contenidoEnvase;
     private String fabricante;
     private Set detallePartidas = new HashSet(0);
     private Set eventoStocks = new HashSet(0);

    public Medicamento() {
    }

	
    public Medicamento(long idMedicamento, String nombreMedicamento, long presentacion, long contenidoEnvase, String fabricante) {
        this.idMedicamento = idMedicamento;
        this.nombreMedicamento = nombreMedicamento;
        this.presentacion = presentacion;
        this.contenidoEnvase = contenidoEnvase;
        this.fabricante = fabricante;
    }
    public Medicamento(long idMedicamento, Stock stock, String nombreMedicamento, long presentacion, long contenidoEnvase, String fabricante, Set detallePartidas, Set eventoStocks) {
       this.idMedicamento = idMedicamento;
       this.stock = stock;
       this.nombreMedicamento = nombreMedicamento;
       this.presentacion = presentacion;
       this.contenidoEnvase = contenidoEnvase;
       this.fabricante = fabricante;
       this.detallePartidas = detallePartidas;
       this.eventoStocks = eventoStocks;
    }
   
    public long getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(long idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public String getNombreMedicamento() {
        return this.nombreMedicamento;
    }
    
    public void setNombreMedicamento(String nombreMedicamento) {
        this.nombreMedicamento = nombreMedicamento;
    }
    public long getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(long presentacion) {
        this.presentacion = presentacion;
    }
    public long getContenidoEnvase() {
        return this.contenidoEnvase;
    }
    
    public void setContenidoEnvase(long contenidoEnvase) {
        this.contenidoEnvase = contenidoEnvase;
    }
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }
    public Set getDetallePartidas() {
        return this.detallePartidas;
    }
    
    public void setDetallePartidas(Set detallePartidas) {
        this.detallePartidas = detallePartidas;
    }
    public Set getEventoStocks() {
        return this.eventoStocks;
    }
    
    public void setEventoStocks(Set eventoStocks) {
        this.eventoStocks = eventoStocks;
    }




}


