package cl.cesfam.ENTITY;
// Generated 25-05-2017 9:08:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MotivoCaducar generated by hbm2java
 */
public class MotivoCaducar  implements java.io.Serializable {


     private int idMotivoCaducar;
     private String nombreMotivoCaducar;
     private Set caducars = new HashSet(0);

    public MotivoCaducar() {
    }

	
    public MotivoCaducar(int idMotivoCaducar, String nombreMotivoCaducar) {
        this.idMotivoCaducar = idMotivoCaducar;
        this.nombreMotivoCaducar = nombreMotivoCaducar;
    }
    public MotivoCaducar(int idMotivoCaducar, String nombreMotivoCaducar, Set caducars) {
       this.idMotivoCaducar = idMotivoCaducar;
       this.nombreMotivoCaducar = nombreMotivoCaducar;
       this.caducars = caducars;
    }
   
    public int getIdMotivoCaducar() {
        return this.idMotivoCaducar;
    }
    
    public void setIdMotivoCaducar(int idMotivoCaducar) {
        this.idMotivoCaducar = idMotivoCaducar;
    }
    public String getNombreMotivoCaducar() {
        return this.nombreMotivoCaducar;
    }
    
    public void setNombreMotivoCaducar(String nombreMotivoCaducar) {
        this.nombreMotivoCaducar = nombreMotivoCaducar;
    }
    public Set getCaducars() {
        return this.caducars;
    }
    
    public void setCaducars(Set caducars) {
        this.caducars = caducars;
    }




}


