package cl.cesfam.ENTITY;
// Generated 16-04-2017 17:23:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private int idPaciente;
     private String rutPaciente;
     private String primerNombrePaciente;
     private String segundoNombrePaciente;
     private String apellidoPaternoPaciente;
     private String apellidoMaternoPaciente;
     private String emailPaciente;
     private String telefonoPaciente;
     private Set eventoStocks = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(String rutPaciente, String primerNombrePaciente, String apellidoPaternoPaciente, String apellidoMaternoPaciente) {
        
        this.rutPaciente = rutPaciente;
        this.primerNombrePaciente = primerNombrePaciente;
        this.apellidoPaternoPaciente = apellidoPaternoPaciente;
        this.apellidoMaternoPaciente = apellidoMaternoPaciente;
    }
    public Paciente(String rutPaciente, String primerNombrePaciente, String segundoNombrePaciente, String apellidoPaternoPaciente, String apellidoMaternoPaciente, String emailPaciente, String telefonoPaciente, Set eventoStocks) {
       
       this.rutPaciente = rutPaciente;
       this.primerNombrePaciente = primerNombrePaciente;
       this.segundoNombrePaciente = segundoNombrePaciente;
       this.apellidoPaternoPaciente = apellidoPaternoPaciente;
       this.apellidoMaternoPaciente = apellidoMaternoPaciente;
       this.emailPaciente = emailPaciente;
       this.telefonoPaciente = telefonoPaciente;
       this.eventoStocks = eventoStocks;
    }
   
    public int getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(int idPaciente) {
        this.idPaciente = idPaciente;
    }
    public String getRutPaciente() {
        return this.rutPaciente;
    }
    
    public void setRutPaciente(String rutPaciente) {
        this.rutPaciente = rutPaciente;
    }
    public String getPrimerNombrePaciente() {
        return this.primerNombrePaciente;
    }
    
    public void setPrimerNombrePaciente(String primerNombrePaciente) {
        this.primerNombrePaciente = primerNombrePaciente;
    }
    public String getSegundoNombrePaciente() {
        return this.segundoNombrePaciente;
    }
    
    public void setSegundoNombrePaciente(String segundoNombrePaciente) {
        this.segundoNombrePaciente = segundoNombrePaciente;
    }
    public String getApellidoPaternoPaciente() {
        return this.apellidoPaternoPaciente;
    }
    
    public void setApellidoPaternoPaciente(String apellidoPaternoPaciente) {
        this.apellidoPaternoPaciente = apellidoPaternoPaciente;
    }
    public String getApellidoMaternoPaciente() {
        return this.apellidoMaternoPaciente;
    }
    
    public void setApellidoMaternoPaciente(String apellidoMaternoPaciente) {
        this.apellidoMaternoPaciente = apellidoMaternoPaciente;
    }
    public String getEmailPaciente() {
        return this.emailPaciente;
    }
    
    public void setEmailPaciente(String emailPaciente) {
        this.emailPaciente = emailPaciente;
    }
    public String getTelefonoPaciente() {
        return this.telefonoPaciente;
    }
    
    public void setTelefonoPaciente(String telefonoPaciente) {
        this.telefonoPaciente = telefonoPaciente;
    }
    public Set getEventoStocks() {
        return this.eventoStocks;
    }
    
    public void setEventoStocks(Set eventoStocks) {
        this.eventoStocks = eventoStocks;
    }




}


