package cl.cesfam.ENTITY;
// Generated 22-05-2017 20:45:04 by Hibernate Tools 4.3.1



/**
 * Prescripcion generated by hbm2java
 */
public class Prescripcion  implements java.io.Serializable {


     private int idPrescripcion;
     private EstadoPrescripcion estadoPrescripcion;
     private FormularioMediamento formularioMediamento;
     private Medicamento medicamento;
     private int periodo;
     private int frecuencia;
     private int tipo;
     private int duracionTratamiento;

    public Prescripcion() {
    }

	
    public Prescripcion(int idPrescripcion) {
        this.idPrescripcion = idPrescripcion;
    }
    public Prescripcion(int idPrescripcion, EstadoPrescripcion estadoPrescripcion, FormularioMediamento formularioMediamento, Medicamento medicamento, int periodo, int frecuencia, int tipo, int duracionTratamiento) {
       this.idPrescripcion = idPrescripcion;
       this.estadoPrescripcion = estadoPrescripcion;
       this.formularioMediamento = formularioMediamento;
       this.medicamento = medicamento;
       this.periodo = periodo;
       this.frecuencia = frecuencia;
       this.tipo = tipo;
       this.duracionTratamiento = duracionTratamiento;
    }
   
    public int getIdPrescripcion() {
        return this.idPrescripcion;
    }
    
    public void setIdPrescripcion(int idPrescripcion) {
        this.idPrescripcion = idPrescripcion;
    }
    public EstadoPrescripcion getEstadoPrescripcion() {
        return this.estadoPrescripcion;
    }
    
    public void setEstadoPrescripcion(EstadoPrescripcion estadoPrescripcion) {
        this.estadoPrescripcion = estadoPrescripcion;
    }
    public FormularioMediamento getFormularioMediamento() {
        return this.formularioMediamento;
    }
    
    public void setFormularioMediamento(FormularioMediamento formularioMediamento) {
        this.formularioMediamento = formularioMediamento;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public int getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(int periodo) {
        this.periodo = periodo;
    }
    public int getFrecuencia() {
        return this.frecuencia;
    }
    
    public void setFrecuencia(int frecuencia) {
        this.frecuencia = frecuencia;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public int getDuracionTratamiento() {
        return this.duracionTratamiento;
    }
    
    public void setDuracionTratamiento(Integer duracionTratamiento) {
        this.duracionTratamiento = duracionTratamiento;
    }




}


