package cl.cesfam.ENTITY;
// Generated 16-04-2017 15:22:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private BigDecimal idStock;
     private BigDecimal stock;
     private BigDecimal stockCritico;
     private Set medicamentos = new HashSet(0);

    public Stock() {
    }

	
    public Stock(BigDecimal idStock, BigDecimal stock, BigDecimal stockCritico) {
        this.idStock = idStock;
        this.stock = stock;
        this.stockCritico = stockCritico;
    }
    public Stock(BigDecimal idStock, BigDecimal stock, BigDecimal stockCritico, Set medicamentos) {
       this.idStock = idStock;
       this.stock = stock;
       this.stockCritico = stockCritico;
       this.medicamentos = medicamentos;
    }
   
    public BigDecimal getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(BigDecimal idStock) {
        this.idStock = idStock;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }
    public BigDecimal getStockCritico() {
        return this.stockCritico;
    }
    
    public void setStockCritico(BigDecimal stockCritico) {
        this.stockCritico = stockCritico;
    }
    public Set getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(Set medicamentos) {
        this.medicamentos = medicamentos;
    }




}


