package cl.cesfam.ENTITY;
// Generated 16-04-2017 17:23:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private int idStock;
     private int stock;
     private int stockCritico;
     private Set medicamentos = new HashSet(0);

    public Stock() {
    }

	
    public Stock(int idStock, int stock, int stockCritico) {
        this.idStock = idStock;
        this.stock = stock;
        this.stockCritico = stockCritico;
    }
    public Stock(int idStock, int stock, int stockCritico, Set medicamentos) {
       this.idStock = idStock;
       this.stock = stock;
       this.stockCritico = stockCritico;
       this.medicamentos = medicamentos;
    }
   
    public int getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(int idStock) {
        this.idStock = idStock;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public int getStockCritico() {
        return this.stockCritico;
    }
    
    public void setStockCritico(int stockCritico) {
        this.stockCritico = stockCritico;
    }
    public Set getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(Set medicamentos) {
        this.medicamentos = medicamentos;
    }




}


