package cl.cesfam.ENTITY;
// Generated 14-04-2017 22:03:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private long idStock;
     private long stock;
     private long stockCritico;
     private Set medicamentos = new HashSet(0);

    public Stock() {
    }

	
    public Stock(long idStock, long stock, long stockCritico) {
        this.idStock = idStock;
        this.stock = stock;
        this.stockCritico = stockCritico;
    }
    public Stock(long idStock, long stock, long stockCritico, Set medicamentos) {
       this.idStock = idStock;
       this.stock = stock;
       this.stockCritico = stockCritico;
       this.medicamentos = medicamentos;
    }
   
    public long getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(long idStock) {
        this.idStock = idStock;
    }
    public long getStock() {
        return this.stock;
    }
    
    public void setStock(long stock) {
        this.stock = stock;
    }
    public long getStockCritico() {
        return this.stockCritico;
    }
    
    public void setStockCritico(long stockCritico) {
        this.stockCritico = stockCritico;
    }
    public Set getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(Set medicamentos) {
        this.medicamentos = medicamentos;
    }




}


