package cl.cesfam.ENTITY;
// Generated 25-05-2017 9:08:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPrescripcion generated by hbm2java
 */
public class TipoPrescripcion  implements java.io.Serializable {


     private int idTipoPrescripcion;
     private String nombreTipoPrescripcion;
     private Set prescripcions = new HashSet(0);

    public TipoPrescripcion() {
    }

	
    public TipoPrescripcion(int idTipoPrescripcion, String nombreTipoPrescripcion) {
        this.idTipoPrescripcion = idTipoPrescripcion;
        this.nombreTipoPrescripcion = nombreTipoPrescripcion;
    }
    public TipoPrescripcion(int idTipoPrescripcion, String nombreTipoPrescripcion, Set prescripcions) {
       this.idTipoPrescripcion = idTipoPrescripcion;
       this.nombreTipoPrescripcion = nombreTipoPrescripcion;
       this.prescripcions = prescripcions;
    }
   
    public int getIdTipoPrescripcion() {
        return this.idTipoPrescripcion;
    }
    
    public void setIdTipoPrescripcion(int idTipoPrescripcion) {
        this.idTipoPrescripcion = idTipoPrescripcion;
    }
    public String getNombreTipoPrescripcion() {
        return this.nombreTipoPrescripcion;
    }
    
    public void setNombreTipoPrescripcion(String nombreTipoPrescripcion) {
        this.nombreTipoPrescripcion = nombreTipoPrescripcion;
    }
    public Set getPrescripcions() {
        return this.prescripcions;
    }
    
    public void setPrescripcions(Set prescripcions) {
        this.prescripcions = prescripcions;
    }




}


